import { Article } from './types/article';

export const articles: Article[] = [
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius felis in arcu auctor sollicitudin. Donec sagittis tortor vel risus vestibulum, non luctus mauris mattis. Vivamus a erat id est egestas imperdiet. Donec et venenatis mi, quis sagittis dolor. Curabitur ligula leo, feugiat at turpis et, tristique vulputate orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet felis purus, quis dapibus est vestibulum elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed egestas, nunc eget pellentesque dapibus, quam quam rhoncus ante, sed gravida mi nunc vel eros. Fusce hendrerit euismod libero, nec sodales nulla. In vitae ligula posuere, eleifend turpis a, dapibus eros. Vestibulum euismod pretium ante nec congue. Donec semper ipsum vel commodo tincidunt. Sed commodo maximus fermentum. Etiam pretium libero tortor. Praesent est turpis, pharetra eu ultricies at, bibendum sed magna.',
    articlePhotoUrl: '',
    id: '1',
    title: "Test Article",
    authorPhotoUrl: 'assets/girl.jpg',
    createdDate: 'June 2022',
    author: 'Anna Eliska',
    topic: 'Sport',
  },
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius felis in arcu auctor sollicitudin. Donec sagittis tortor vel risus vestibulum, non luctus mauris mattis. Vivamus a erat id est egestas imperdiet. Donec et venenatis mi, quis sagittis dolor. Curabitur ligula leo, feugiat at turpis et, tristique vulputate orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet felis purus, quis dapibus est vestibulum elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed egestas, nunc eget pellentesque dapibus, quam quam rhoncus ante, sed gravida mi nunc vel eros. Fusce hendrerit euismod libero, nec sodales nulla. In vitae ligula posuere, eleifend turpis a, dapibus eros. Vestibulum euismod pretium ante nec congue. Donec semper ipsum vel commodo tincidunt. Sed commodo maximus fermentum. Etiam pretium libero tortor. Praesent est turpis, pharetra eu ultricies at, bibendum sed magna.',
    articlePhotoUrl: '',
    id: '1',
    title: "Test Article",
    authorPhotoUrl: 'assets/girl.jpg',
    createdDate: 'June 2022',
    author: 'Anna Eliska',
    topic: 'Sport',
  },
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius felis in arcu auctor sollicitudin. Donec sagittis tortor vel risus vestibulum, non luctus mauris mattis. Vivamus a erat id est egestas imperdiet. Donec et venenatis mi, quis sagittis dolor. Curabitur ligula leo, feugiat at turpis et, tristique vulputate orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet felis purus, quis dapibus est vestibulum elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed egestas, nunc eget pellentesque dapibus, quam quam rhoncus ante, sed gravida mi nunc vel eros. Fusce hendrerit euismod libero, nec sodales nulla. In vitae ligula posuere, eleifend turpis a, dapibus eros. Vestibulum euismod pretium ante nec congue. Donec semper ipsum vel commodo tincidunt. Sed commodo maximus fermentum. Etiam pretium libero tortor. Praesent est turpis, pharetra eu ultricies at, bibendum sed magna.',
    articlePhotoUrl: '',
    id: '1',
    title: "Test Article",
    authorPhotoUrl: 'assets/girl.jpg',
    createdDate: 'June 2022',
    author: 'Anna Eliska',
    topic: 'Sport',
  },
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius felis in arcu auctor sollicitudin. Donec sagittis tortor vel risus vestibulum, non luctus mauris mattis. Vivamus a erat id est egestas imperdiet. Donec et venenatis mi, quis sagittis dolor. Curabitur ligula leo, feugiat at turpis et, tristique vulputate orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet felis purus, quis dapibus est vestibulum elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed egestas, nunc eget pellentesque dapibus, quam quam rhoncus ante, sed gravida mi nunc vel eros. Fusce hendrerit euismod libero, nec sodales nulla. In vitae ligula posuere, eleifend turpis a, dapibus eros. Vestibulum euismod pretium ante nec congue. Donec semper ipsum vel commodo tincidunt. Sed commodo maximus fermentum. Etiam pretium libero tortor. Praesent est turpis, pharetra eu ultricies at, bibendum sed magna.',
    articlePhotoUrl: '',
    id: '1',
    title: "Test Article",
    authorPhotoUrl: 'assets/girl.jpg',
    createdDate: 'June 2022',
    author: 'Anna Eliska',
    topic: 'Sport',
  },
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius felis in arcu auctor sollicitudin. Donec sagittis tortor vel risus vestibulum, non luctus mauris mattis. Vivamus a erat id est egestas imperdiet. Donec et venenatis mi, quis sagittis dolor. Curabitur ligula leo, feugiat at turpis et, tristique vulputate orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet felis purus, quis dapibus est vestibulum elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed egestas, nunc eget pellentesque dapibus, quam quam rhoncus ante, sed gravida mi nunc vel eros. Fusce hendrerit euismod libero, nec sodales nulla. In vitae ligula posuere, eleifend turpis a, dapibus eros. Vestibulum euismod pretium ante nec congue. Donec semper ipsum vel commodo tincidunt. Sed commodo maximus fermentum. Etiam pretium libero tortor. Praesent est turpis, pharetra eu ultricies at, bibendum sed magna.',
    articlePhotoUrl: '',
    id: '1',
    title: "Test Article",
    authorPhotoUrl: 'assets/girl.jpg',
    createdDate: 'June 2022',
    author: 'Anna Eliska',
    topic: 'Sport',
  },
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius felis in arcu auctor sollicitudin. Donec sagittis tortor vel risus vestibulum, non luctus mauris mattis. Vivamus a erat id est egestas imperdiet. Donec et venenatis mi, quis sagittis dolor. Curabitur ligula leo, feugiat at turpis et, tristique vulputate orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet felis purus, quis dapibus est vestibulum elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed egestas, nunc eget pellentesque dapibus, quam quam rhoncus ante, sed gravida mi nunc vel eros. Fusce hendrerit euismod libero, nec sodales nulla. In vitae ligula posuere, eleifend turpis a, dapibus eros. Vestibulum euismod pretium ante nec congue. Donec semper ipsum vel commodo tincidunt. Sed commodo maximus fermentum. Etiam pretium libero tortor. Praesent est turpis, pharetra eu ultricies at, bibendum sed magna.',
    articlePhotoUrl: '',
    id: '1',
    title: "Test Article",
    authorPhotoUrl: 'assets/girl.jpg',
    createdDate: 'June 2022',
    author: 'Anna Eliska',
    topic: 'Sport',
  },
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius felis in arcu auctor sollicitudin. Donec sagittis tortor vel risus vestibulum, non luctus mauris mattis. Vivamus a erat id est egestas imperdiet. Donec et venenatis mi, quis sagittis dolor. Curabitur ligula leo, feugiat at turpis et, tristique vulputate orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet felis purus, quis dapibus est vestibulum elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed egestas, nunc eget pellentesque dapibus, quam quam rhoncus ante, sed gravida mi nunc vel eros. Fusce hendrerit euismod libero, nec sodales nulla. In vitae ligula posuere, eleifend turpis a, dapibus eros. Vestibulum euismod pretium ante nec congue. Donec semper ipsum vel commodo tincidunt. Sed commodo maximus fermentum. Etiam pretium libero tortor. Praesent est turpis, pharetra eu ultricies at, bibendum sed magna.',
    articlePhotoUrl: '',
    id: '1',
    title: "Test Article",
    authorPhotoUrl: 'assets/girl.jpg',
    createdDate: 'June 2022',
    author: 'Anna Eliska',
    topic: 'Sport',
  },
];
